package com.mcp.policies;

import org.springframework.stereotype.Component;

@Component
public class McpSafetyPolicy {

    public void enforceReadOnly() {
        // Enforce that only read-only services/methods are accessed.
        // This is primarily a logical boundary in this architecture.
    }

    public String getGuardrailMessage() {
        return "Disclaimer: This analysis is based on rule-based insights generated by the core system. " +
                "It is NOT financial advice. The AI is a translator of existing system context.";
    }
}
